using System.Collections.Generic;

namespace BeagleStreet.JourneyRunner.Models
{
    public class TravelInfo
    {
        public bool KnowsWhichCountryTheyWillTravelTo { get; set; }
        public string Country { get; set; }
        public bool IntendToLiveInCountrySelected { get; set; }

        public static int GetIndexOfCountry(string country)
        {
            return LoadCountries().IndexOf(country);
        }

        public static List<string> LoadCountries()
        {
            return new List<string>
            {
                "Afghanistan", 
                "Albania",
                "Algeria",
                "American Samoa",
                "Andorra",
                "Angola",
                "Anguilla",
                "Antigua and Barbuda",
                "Antilles",
                "Argentina",
                "Armenia",
                "Aruba",
                "Australlia",
                "Austria",
                "Azerbaijan",
                "Azores",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belguim",
                "Belize",
                "Benin",
                "Bermuda",
                "Bolivia",
                "Bosnia-Herzegovina",
                "Botswana",
                "Brazil",
                "British Virgin Islands",
                "Brunei",
                "Bulgaria",
                "Burkina-Faso",
                "Burma",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Canary Islands",
                "Cape Verde",
                "Cayman Islands",
                "Central African Republic",
                "Chad",
                "Channel Islands",
                "Chechen Republic",
                "Chechnya",
                "Chile",
                "China",
                "Christmas Islands",
                "Colombia",
                "Comoros",
                "Congo",
                "Cook Islands",
                "Costa Rica",
                "Cote d'Ivoire",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic",
                "Democratic Republic of Congo",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "East Timor",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Falkland Islands",
                "Faroe Islands",
                "Fiji",
                "Finland",
                "France",
                "French Guiana",
                "French Polynesia",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Gibraltar",
                "Grand Turk and Caicos",
                "Greece",
                "Greenland",
                "Grenada",
                "Guadeloupe",
                "Guam",
                "Guatemala",
                "Guernsey",
                "Guiana",
                "Guinea",
                "Guinea-Bissau",
                "Haiti",
                "Holland",
                "Honduras",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Isle of Man",
                "Israel",
                "Italy",
                "Ivory Coast",
                "Jamiaca",
                "Japan",
                "Jersey",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Kosovo",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macau",
                "Macedonia",
                "Madagascar",
                "Madeira",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Martinique",
                "Mauritinia",
                "Mauritius",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Montserrat",
                "Morocco",
                "Mozambique",
                "Myanmar",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "Netherlands Antilles",
                "New Caledonia",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "Niue",
                "Norfolk Island",
                "North Korea",
                "Norway",
                "Oman",
                "Pakistan",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Pitcairn Island",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Qatar",
                "Republic of Ireland",
                "Reunion",
                "Romania",
                "Russia",
                "Rwanda",
                "Samoa",
                "San Marino",
                "Sao Tome and Principe",
                "Saudi Arabia",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Korea",
                "Spain",
                "Sri Lanka",
                "St Kitts and Nevis",
                "St Lucia",
                "St Martin",
                "St Vincent and the Grenadines",
                "Sudan",
                "Suriname",
                "Swaziland",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Tibet",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United Kingdom",
                "United States of America",
                "Uruguay",
                "US Virgin Islands",
                "Uzbekistan",
                "Vanuatu",
                "Venezuala",
                "Vietnam",
                "Wallis and Futuna Islands",
                "Western Sahara",
                "Western Samoa",
                "Yemen",
                "Zaire",
                "Zambia",
                "Zimbabwe"
            };
        }
    }
}
